"""Update task status and priority to use enums

Revision ID: c8f14323534a
Revises: 3c4345435435
Create Date: 2025-07-03 21:03:02.925462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c8f14323534a'
down_revision = '3c4345435435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE taskstatus AS ENUM ('pending', 'in_progress', 'completed', 'cancelled')")
    op.execute("CREATE TYPE taskpriority AS ENUM ('low', 'medium', 'high')")

    # Update existing 'pendiente' values to 'pending' before altering column type
    op.execute("UPDATE task SET status = 'pending' WHERE status = 'pendiente'")

    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='taskstatus', create_type=False),
               existing_nullable=False,
               postgresql_using='status::taskstatus')

    # Update existing 'media' values to 'medium' before altering column type
    op.execute("UPDATE task SET priority = 'medium' WHERE priority = 'media'")

    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('low', 'medium', 'high', name='taskpriority', create_type=False),
               existing_nullable=False,
               postgresql_using='priority::taskpriority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', name='taskpriority', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('task', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='taskstatus', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.execute("DROP TYPE taskstatus")
    op.execute("DROP TYPE taskpriority")
    # ### end Alembic commands ###
